name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      # install practical NuGet
      - name: Install GitHub Pages helper NuGet
        run: dotnet add ./src/BlazingNotes.WasmApp/ package PublishSPAforGitHubPages.Build --version 2.2.0
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish ./src/BlazingNotes.WasmApp/ -c:Release -p:GHPages=true -o ./publish/ --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: ./publish/wwwroot/
